### ISSUE TITLE
Example  Can not operate

### ISSUE THREAD

**Issue by Pobby12** [bharathraj-e/g_recaptcha_v3#5]
Thanks for sharing, I downloaded the example, but it doesn't work.Do you need any other configuration?
![image](https://user-images.githubusercontent.com/16573766/148740872-c12a6623-cac2-4546-9b54-be2ebcc7116d.png)

**Comment by bharathraj-e** [comment]
<img width="652" alt="Screenshot 2022-01-11 at 10 21 26 AM" src="https://user-images.githubusercontent.com/30995464/148883206-7909fd4c-3216-46ca-9da8-8dbbb66be8bf.png">
Try: (In example pubspec.yaml)
Replace 
    
    g_recaptcha_v3:
      path: ../

with (exact version)

    g_recaptcha_v3: ^0.0.4

if the issue still persists, provide the browser console log

**Comment by Pobby12** [comment]
console log:
TypeError: Cannot set properties of undefined (setting 'flutter_g_recaptcha_v3_key')
at ready (http://localhost:58104/packages/g_recaptcha_v3/g_recaptcha_v3_web.dart.lib.js:64:59)
    at ready.next (<anonymous>)
    at runBody (http://localhost:58104/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58104/dart_sdk.js:40242:7)
at Function.ready (http://localhost:58104/packages/g_recaptcha_v3/g_recaptcha_v3_web.dart.lib.js:62:20)
at ready (http://localhost:58104/packages/g_recaptcha_v3/g_recaptcha_v3.dart.lib.js:21:64)
    at ready.next (<anonymous>)
    at runBody (http://localhost:58104/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58104/dart_sdk.js:40242:7)
at Function.ready (http://localhost:58104/packages/g_recaptcha_v3/g_recaptcha_v3.dart.lib.js:20:20)
at main (http://localhost:58104/packages/g_recaptcha_v3_example/main.dart.lib.js:512:41)
    at main.next (<anonymous>)
    at runBody (http://localhost:58104/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58104/dart_sdk.js:40242:7)
at main$ (http://localhost:58104/packages/g_recaptcha_v3_example/main.dart.lib.js:510:18)
at main (http://localhost:58104/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:58104/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:58104/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:58104/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58104/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58104/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58104/dart_sdk.js:35437:23)
    at http://localhost:58104/dart_sdk.js:34617:46
    at _RootZone.runUnary (http://localhost:58104/dart_sdk.js:40062:59)
    at _FutureListener.then.handleValue (http://localhost:58104/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:58104/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:58104/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:58104/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58104/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:58104/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:58104/dart_sdk.js:40336:13)
    at http://localhost:58104/dart_sdk.js:35811:9

**Comment by bharathraj-e** [comment]
Package updated!
Please reopen this issue if the issue persists.
_(Sorry for the delay)_
